config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'portal/dentists#index'
  namespace :admin do
    root 'notifications#index'
    resources :notifications
    resource :sessions, only: [:new, :create, :destroy]
  end

  namespace :portal do
    resources :dentists
    resources :abouts, only: :index
    resources :director_introducings, only: :index
    resources :facilities, only: :index
    resources :flow_examinations, only: :index
    resources :visit_to_visits, only: :index
    resources :time_and_accesses, only: :index
    resources :recruits, only: :index
  end
end

app/models/admin/notification.rb
# frozen_string_literal: true

class Admin::Notification < ApplicationRecord
end

app/controllers/admin/notifications_controller.rb
# frozen_string_literal: true

class Admin::NotificationsController < ApplicationController
  layout 'admin'
  before_action :set_admin_notification, only: %i[show edit update destroy]

  # GET /admin/notifications
  # GET /admin/notifications.json
  def index
    @admin_notifications = Admin::Notification.all
  end

  # GET /admin/notifications/1
  # GET /admin/notifications/1.json
  def show; end

  # GET /admin/notifications/new
  def new
    @admin_notification = Admin::Notification.new
  end

  # GET /admin/notifications/1/edit
  def edit; end

  # POST /admin/notifications
  # POST /admin/notifications.json
  def create
    # raise "#{admin_notification_params[:text].gsub(/\R/, "\n")}"
    @admin_notification = Admin::Notification.new(admin_notification_params)

    respond_to do |format|
      if @admin_notification.save
        format.html { redirect_to @admin_notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @admin_notification }
      else
        format.html { render :new }
        format.json { render json: @admin_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/notifications/1
  # PATCH/PUT /admin/notifications/1.json
  def update
    respond_to do |format|
      if @admin_notification.update(admin_notification_params)
        format.html { redirect_to @admin_notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_notification }
      else
        format.html { render :edit }
        format.json { render json: @admin_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/notifications/1
  # DELETE /admin/notifications/1.json
  def destroy
    @admin_notification.destroy
    respond_to do |format|
      format.html { redirect_to admin_notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_notification
    @admin_notification = Admin::Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_notification_params
    params.require(:admin_notification).permit(:text)
  end
end

app/helpers/admin/notifications_helper.rb
# frozen_string_literal: true

module Admin::NotificationsHelper
end

app/views/admin/notifications/_form.html.haml
= form_for @admin_notification do |f|
  - if @admin_notification.errors.any?
    #error_explanation
      %h2= pluralize(@admin_notification.errors.count, "error")
      %ul
        - @admin_notification.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :text, 'お知らせ内容'
    = f.text_area :text, class: 'form-control'
  .actions
    = link_to '戻る', admin_notifications_path, class: 'btn btn-info'
    = f.submit '保存', class: 'btn btn-primary'

app/views/admin/notifications/edit.html.haml
%h2 編集

= render 'form'

app/views/admin/notifications/index.html.haml
%h2 お知らせ一覧
.table-responsive
  %table.table.text-nowrap.table-bordered.table-striped
    %thead.thead-light
      %tr
        %th お知らせ内容
        %th
    %tbody
      - @admin_notifications.each do |admin_notification|
        %tr
          %td= admin_notification.text.truncate(30)
          %td.text-right
            = link_to 'プレビュー', admin_notification, class: 'btn btn-info'
            = link_to '編集', edit_admin_notification_path(admin_notification), class: 'btn btn-success'
            = link_to '削除', admin_notification, method: :delete,
              data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger'

= link_to '新規作成', new_admin_notification_path, class: 'btn btn-primary'

app/views/admin/notifications/new.html.haml
%h2 新規作成

= render 'form'

app/views/admin/notifications/show.html.haml
%h2 プレビュー
%p#notice
  - if notice.present?
    .alert.alert-success= notice

.card.mb-3
  %h5.card-header お知らせ内容
  .card-body= raw Rinku.auto_link(simple_format(@admin_notification.text))

= link_to '戻る', admin_notifications_path, class: 'btn btn-info'
= link_to '編集', edit_admin_notification_path(@admin_notification), class: 'btn btn-success'