config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'portal/dentists#index'
  namespace :admin do
    root 'notifications#index'
    resources :notifications
    resource :sessions, only: [:new, :create, :destroy]
  end

  namespace :portal do
    resources :dentists
    resources :abouts, only: :index
    resources :director_introducings, only: :index
    resources :facilities, only: :index
    resources :flow_examinations, only: :index
    resources :visit_to_visits, only: :index
    resources :time_and_accesses, only: :index
    resources :recruits, only: :index
  end
end

app/controllers/portal/abouts_controller.rb
# frozen_string_literal: true

class Portal::AboutsController < ApplicationController
  # GET /portal/abouts
  # GET /portal/abouts.json
  def index
    @portal_abouts = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/controllers/portal/dentists_controller.rb
# frozen_string_literal: true

class Portal::DentistsController < ApplicationController
  before_action :set_portal_dentist, only: %i[show edit update destroy]
  before_action :set_index_variable, only: %i[index]

  # GET /portal/dentists
  # GET /portal/dentists.json
  def index
    @notification = Admin::Notification.all

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      render :index_smart_phone, layout: 'smart_phone.html.haml'
      return
    end
  end

  # GET /portal/dentists/1
  # GET /portal/dentists/1.json
  def show; end

  # GET /portal/dentists/new
  def new
    @portal_dentist = Portal::Dentist.new
  end

  # GET /portal/dentists/1/edit
  def edit; end

  # POST /portal/dentists
  # POST /portal/dentists.json
  def create
    @portal_dentist = Portal::Dentist.new(portal_dentist_params)

    respond_to do |format|
      if @portal_dentist.save
        format.html { redirect_to @portal_dentist, notice: 'Dentist was successfully created.' }
        format.json { render :show, status: :created, location: @portal_dentist }
      else
        format.html { render :new }
        format.json { render json: @portal_dentist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portal/dentists/1
  # PATCH/PUT /portal/dentists/1.json
  def update
    respond_to do |format|
      if @portal_dentist.update(portal_dentist_params)
        format.html { redirect_to @portal_dentist, notice: 'Dentist was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal_dentist }
      else
        format.html { render :edit }
        format.json { render json: @portal_dentist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portal/dentists/1
  # DELETE /portal/dentists/1.json
  def destroy
    @portal_dentist.destroy
    respond_to do |format|
      format.html { redirect_to portal_dentists_url, notice: 'Dentist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_portal_dentist
    @portal_dentist = Portal::Dentist.find(params[:id])
  end

  def set_index_variable
    @portal_dentists = []
    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
    else
      set_contents
    end

    set_sticking
  end

  def set_sticking
    @sticking = [
      { title: "① かかりつけ歯科医機能強化型歯科診療所に認定",
        img: 'かかりつけ機能強化型.JPG',
        text: "当院は多くの高度な施設基準や実績をクリアしているため皆様に安心して受診して頂けます。\
              またこの基準をクリアしているため、皆様のお口の健康をより詳細に管理する事が可能となりました。\
              \n※この施設基準をクリアしている歯科医院は全国の医院の10%ほどだけです。",
        details: true },
      { title: '② 複数の歯科衛生士の在籍',
        img: '複数の衛生士の在籍.JPG',
        text: "国家資格を有するプロの歯科衛生士があなたのお口の中の健康管理を責任を持って行います。\
              また、複数の衛生士が在籍しておりますので、予約も出来るだけお待たせ致しません。",
        details: true },
      { title: '③ 徹底した衛生管理',
        img: 'sticking2.jpg',
        text: '清潔な院内環境作りと最高レベルの滅菌機器で、徹底した衛生管理に勤めています。',
        details: true },
      { title: '④ 車が停めやすい広々駐車場',
        img: '駐車場.JPG',
        text: "最大駐車数20台。\n 広い駐車スペースで安心した通院を実現。\n ※駐車が苦手な女性でも安心して止められます",
        details: false },
      { title: '⑤ 訪問診療の実施',
        img: 'sticking5.jpg',
        text: "当院は訪問診療の実績が２０年以上あります。\n要介護の高齢者や体に障害がある等で通院が困難な方に対して施設やご自宅まで訪問させて頂きます。",
        details: true },
      { title: '⑥ 検査結果のお渡し',
        img: 'sticking3.jpg',
        text: '患者様自身でご自身の口腔状況を把握していただきやすいよう。検査結果を印刷してお渡ししております。',
        details: false },
      { title: '⑦  広々とした診療室',
        img: 'sticking6.jpg',
        text: "広々とした診療室をご用意させていただいております。ベビーカーと一緒に診療室へ入れます。\nベビーカーや車椅子のお客様もご安心してご来院ください。",
        details: false }
    ]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def portal_dentist_params
    params.fetch(:portal_dentist, {})
  end
end

app/controllers/portal/director_introducings_controller.rb
# frozen_string_literal: true

class Portal::DirectorIntroducingsController < ApplicationController
  # GET /portal/director_introducings
  # GET /portal/director_introducings.json
  def index
    @portal_director_introducings = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/controllers/portal/facilities_controller.rb
# frozen_string_literal: true

class Portal::FacilitiesController < ApplicationController
  # GET /portal/facilities
  # GET /portal/facilities.json
  def index
    @portal_facilities = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/controllers/portal/flow_examinations_controller.rb
# frozen_string_literal: true

class Portal::FlowExaminationsController < ApplicationController
  # GET /portal/flow_examinations
  # GET /portal/flow_examinations.json
  def index
    @portal_flow_examinations = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/controllers/portal/recruits_controller.rb
# frozen_string_literal: true

class Portal::RecruitsController < ApplicationController
  # GET /portal/recruits
  # GET /portal/recruits.json
  def index
    @portal_recruits = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/controllers/portal/time_and_accesses_controller.rb
# frozen_string_literal: true

class Portal::TimeAndAccessesController < ApplicationController
  # GET /portal/time_and_accesses
  # GET /portal/time_and_accesses.json
  def index
    @portal_time_and_accesses = []

    if request.smart_phone?
      set_contents_sp

      render :index_smart_phone, layout: 'smart_phone.html.haml'
    end
  end
end

app/controllers/portal/visit_to_visits_controller.rb
# frozen_string_literal: true

class Portal::VisitToVisitsController < ApplicationController
  # GET /portal/visit_to_visits
  # GET /portal/visit_to_visits.json
  def index
    @portal_visit_to_visits = []

    unless request.from_pc? || request.from_android_tablet? || request.from_ipad?
      set_contents_sp
      render :index_smart_phone, layout: 'smart_phone.html.haml'
    else
      set_contents
      return
    end
  end
end

app/helpers/portal/abouts_helper.rb
# frozen_string_literal: true

module Portal::AboutsHelper
end

app/helpers/portal/dentists_helper.rb
# frozen_string_literal: true

module Portal::DentistsHelper
end

app/helpers/portal/director_introducings_helper.rb
# frozen_string_literal: true

module Portal::DirectorIntroducingsHelper
end

app/helpers/portal/facilities_helper.rb
# frozen_string_literal: true

module Portal::FacilitiesHelper
end

app/helpers/portal/flow_examinations_helper.rb
# frozen_string_literal: true

module Portal::FlowExaminationsHelper
end

app/helpers/portal/recruits_helper.rb
# frozen_string_literal: true

module Portal::RecruitsHelper
end

app/helpers/portal/time_and_accesses_helper.rb
# frozen_string_literal: true

module Portal::TimeAndAccessesHelper
end

app/helpers/portal/visit_to_visits_helper.rb
# frozen_string_literal: true

module Portal::VisitToVisitsHelper
end

app/views/portal/dentists/_footer.html.haml
.container.pt-5.mb-3.pb-5
  .card-deck
    .card
      .card-body
        .card-title アクセス
        %p.card-text 名鉄津島線　藤浪駅より徒歩3分
        %p.card-text
          %iframe{:allowfullscreen => "", :frameborder => "0", :height => "400", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3260.7626734241003!2d136.7355441151482!3d35.18746726450014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x600398edc0cae3f5%3A0x3c4ac376b43c5257!2z44GE44GX44GM44GN5q2v56eR!5e0!3m2!1sja!2sjp!4v1560217945947!5m2!1sja!2sjp", :style => "border:0", :width => "100%"}
    .card
      .card-body
        %p.card-text 院内風景
        %p.card-text
          %iframe{:allowfullscreen => "", :frameborder => "0", :height => "450", :src => "https://www.google.com/maps/embed?pb=!4v1558424278271!6m8!1m7!1sCAoSLEFGMVFpcFBrazIybnR3OGxZaUtubWpNaHlpSmV3Y2N5YnpyeGxtU2R0eFpM!2m2!1d35.18772203479!2d136.73787814582!3f145.00485225452962!4f-9.72329895937304!5f0.7820865974627469", :style => "border:0", :width => "100%"}
  .row.mt-5.pt-4
    .col-12
      .google-calendar
        .wrap
          %iframe{:frameborder => "0", :height => "600", :width => "100%", :src => "https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%239ff59f&ctz=Asia%2FTokyo&src=NHJudWV0ZHFsbzlucnFqNzloMDV2YmhuNWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%230B8043&showTitle=0&showPrint=0&showTabs=1&showCalendars=0&showTz=0", :style => "border:solid 1px #777", :width => "100%"}
.container.mb-5.mt-5
  .row
    .col-5= image_tag('footer_left.png', alt: 'いしがき歯科', class: 'img-fluid')
    .col-1
    .col-6= image_tag('footer_right.png', alt: '診療時間', class: 'img-fluid')

app/views/portal/dentists/_form.html.haml
= form_for @portal_dentist do |f|
  - if @portal_dentist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@portal_dentist.errors.count, "error")} prohibited this portal_dentist from being saved:"
      %ul
        - @portal_dentist.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/portal/dentists/_header.html.haml
.container
  .row.pt-1
    %h1.col-4= image_tag('logo.png', alt: 'いしがき歯科', class: 'img-fluid')
    .col-1
    .col-4.pt-3
      = image_tag('medical_hours.png', alt: '診療時間', class: 'img-fluid')
    .col-3.pt-3
      = image_tag('query.png', alt: '診療時間', class: 'img-fluid')

.container
  %div.pt-5{ class: request.from_pc? ? 'clinic-img-wrapper' : 'clinic-img-wrapper-pad' }
    %ul#fade
      - (1..5).each do |i|
        %li= image_tag("slide#{i}.jpg", alt: '医院', class: "")

app/views/portal/dentists/_navbar_smart_phone.html.haml
.collapse.navbar-collapse
  %ul.navbar-nav.mx-auto
    - contents.each do |c|
      %li.nav-item.text-center.active
        = link_to '#', class: 'nav-link' do
          - if c[:img_name].kind_of?(Array)
            = image_tag c[:img_name].first, class: 'nav-link-icon'
            = image_tag c[:img_name].second, class: 'nav-link-icon'
          - else
            = image_tag c[:img_name], class: 'nav-link-icon'
          %br
          .nav-text= c[:text]

app/views/portal/dentists/_navber.html.haml
.collapse.navbar-collapse
  %ul.navbar-nav.mx-auto
    - contents.each do |c|
      %li.nav-item.text-center
        = link_to c[:link], class: 'nav-link' do
          = image_tag c[:img_name], class: 'nav-link-icon-pd'
          %br
          .nav-text-pd= c[:text]

app/views/portal/dentists/edit.html.haml
%h1 Editing portal_dentist

= render 'form'

= link_to 'Show', @portal_dentist
\|
= link_to 'Back', portal_dentists_path

app/views/portal/dentists/index.html.haml
.bg-h
  .container.pt-3.pb-5
    .row
      .col-12
        .card-deck
          .card
            .card-body
              %h5.card-title
                %i.fas.fa-comment-alt
                %span 院長からのメッセージ
              %p.card-text
                .news-table
                  %table.table
                    %tbody
                      - @notification.each do |n|
                        %tr
                          %td= n.created_at.strftime('%Y/%m/%d')
                        %tr
                          %td= raw Rinku.auto_link(simple_format(n.text))
          .card.b-none
            .card-body
              %h5= link_to image_tag('110499.jpg', { class: 'img-fluid', :border => '0',
                :alt => 'ドクターズファイル'}), 'https://doctorsfile.jp/h/110499/df/1/'

  .container.pt-3
    .row
      .col-12
        %h3
          %span
            -# = image_tag('icon_doctor.png', alt: '', class: 'tc-b-img')
            %i.fas.fa-tooth.pb-1
            %span いしがき歯科の特徴

  - stickings = @sticking.each_slice(2).to_a
  .container
    - stickings.each do |sticking|
      - if sticking.length > 1
        .card-deck
          - sticking.each_with_index do |s, i|
            .card.mb-3
              .card-body
                %h5.card-title= s[:title]
                %p.card-text= image_tag(s[:img], alt: '医院', class: 'sticking-img')
                %p.card-text= simple_format(s[:text])
      - else
        .card-group.hrf
          .card.mb-3.mr-3
            .card-body
              %h5.card-title= sticking[0][:title]
              %p.card-text= image_tag(sticking[0][:img], alt: '医院', class: 'sticking-img')
              %p.card-text= simple_format(sticking[0][:text])

app/views/portal/dentists/index_smart_phone.html.haml
.container.pt-5.pb-5
  .row
    .col-12= link_to image_tag('110499.jpg', { class: 'img-fluid', :border => '0',
      :alt => 'ドクターズファイル'}), 'https://doctorsfile.jp/h/110499/df/1/'

.container.news
  .row.pt-3
    .col-12.text-left
      %h4.border-bottom.tc-b 院長からのメッセージ
  .row.pb-3
    .col-12
      .news-table
        %table.table
          %tbody
            - @notification.each do |n|
              %tr
                %td= n.created_at.strftime('%Y/%m/%d')
              %tr
                %td= raw Rinku.auto_link(simple_format(n.text))

.sticking
  .container
    .row.pb-3.pt-4
      .col-12.pr-3.pl-3
        %h4.border-bottom
          %span
            %i.fas.fa-tooth.pb-1.tc-b
            %span.tc-b いしがき歯科の特徴
    - sticking = @sticking
    .row.pb-3.pl-2.pr-2
      - sticking.each_with_index do |s, i|
        .col-6.mb-3.pr-2.pl-2
          %div{class: (i == 0 || i == 1) ? 'bg-white-area' : 'bg-white-area2'}
            .row.pb-3
              .col-12{class: (i == 0 || i == 1) ? 'title' : 'title2'}= s[:title]
            .row
              .col-12.pb-3= image_tag(s[:img], alt: '医院', class: 'sticking-img')
            .row
              .col-12.text=simple_format(s[:text])

app/views/portal/dentists/new.html.haml
%h1 New portal_dentist

= render 'form'

= link_to 'Back', portal_dentists_path

app/views/portal/dentists/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_portal_dentist_path(@portal_dentist)
\|
= link_to 'Back', portal_dentists_path